In [ ]:
# Student name: Benjamin Rabishaw
# Student number: 1001556522
# Instructor: Shion Guha
# Course code: INF2178
# Course name: Experimental Design for Data Science
# Program: Master of Information
# Faculty of Information
# University of Toronto


# Technical Assignment 2
# March 9, 2024

In [117]:
# Initiating relevant libraries and packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import shapiro
from scipy.stats import levene
from scipy.stats import f_oneway
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import statsmodels.api as sm
import seaborn as sns
from scipy import stats

In [ ]:
# Integrating Google Drive

from google.colab import drive
drive.mount('/drive', force_remount=True)

Mounted at /drive

In [70]:
# Loading Dataset and surveying first rows

df = pd.read_excel('/drive/MyDrive/UofT/Colab/Files/INF2178_A2_data.xlsx')
df.head(25)

,_id,LOC_ID,LOC_NAME,AUSPICE,ADDRESS,PCODE,ward,bldg_type,BLDGNAME,IGSPACE,TGSPACE,PGSPACE,KGSPACE,SGSPACE,TOTSPACE,subsidy,cwelcc_flag
0,1,1013,Lakeshore Community Child Care Centre,Non Profit Agency,101 SEVENTH ST,M8V 3B5,3,Public Elementary School,Seventh Street Public School,0,20,32,52,60,164,Y,Y
1,2,1014,Alternative Primary School Parent Group,Non Profit Agency,1100 SPADINA RD,M5N 2M6,8,Public Elementary School,North Preparatory Public School,0,0,12,26,45,83,Y,Y
2,3,1015,Cardinal Leger Child Care Centre (Scarborough),Non Profit Agency,600 MORRISH RD,M1C 4Y1,25,Catholic Elementary School,Cardinal Leger Catholic School,0,10,16,26,50,102,Y,Y
3,4,1016,George Brown - Richmond Adelaide Childcare Centre,Non Profit Agency,130 ADELAIDE ST W,M5H 3P5,10,Other,NaN,10,15,40,0,0,65,Y,Y
4,5,1017,Woodland Nursery School (Warden Woods Communit...,Non Profit Agency,1 FIRVALLEY CRT,M1L 1N8,20,High Rise Apartment,NaN,0,10,16,0,0,26,Y,Y
5,6,1021,Centennial College Progress Campus Child Care ...,Non Profit Agency,941 PROGRESS AVE,M1G 3T8,24,Community College/University,Centennial College Of Applied Arts & Technology,10,20,32,0,0,62,Y,Y
6,7,1029,Air-O-Down Child Care Centre,Non Profit Agency,7 HAWKSDALE RD,M3K 1W3,6,Public High School,Downsview Secondary School,10,15,24,0,0,49,Y,Y
7,8,1031,Cedarbrae Day Nurseries (20 Greencrest),Commercial Agency,20 GREENCREST CIRCT,M1G 1B8,24,High Rise Apartment,Greencrest Property,0,0,16,0,30,46,Y,Y
8,9,1037,Tiago Avenue Community Child Care,Non Profit Agency,145 TIAGO AVE,M4B 2A6,19,Public Elementary School,Victoria Park Public School,0,0,21,0,30,51,Y,Y
9,10,1041,Ledbury Park Child Care Program,Non Profit Agency,95 FALKIRK ST,M5M 4K1,8,Public Elementary School,Ledbury Park Public School,0,0,24,39,90,153,Y,Y
10,11,1044,Alderwood Action After School,Non Profit Agency,544 HORNER AVE,M8W 2C2,3,Public Elementary School,Sir Adam Beck School,0,15,32,52,90,189,Y,Y
11,12,1045,Children's Village Day Care Centre #1,Commercial Agency,1050 MARKHAM RD,M1H 2Y7,24,High Rise Apartment,NaN,10,10,32,12,30,94,Y,Y
12,13,1046,Ferncliff Daycare And After School Group,Non Profit Agency,128 FERN AVE,M6R 1K3,4,Public Elementary School,Fern Avenue Junior And Senior Public School,0,0,32,52,100,184,Y,Y
13,14,1055,Balmy Beach Community Day Care Centre,Non Profit Agency,14 PINE AVE,M4E 1L6,19,Public Elementary School,Balmy Beach Public School,0,0,16,52,75,143,Y,Y
14,15,1060,Braeburn Woods Day Care Centre,Non Profit Agency,30 HAREFIELD DR,M9W 4C9,1,Public Elementary School,Braeburn Junior School,0,10,16,25,30,81,Y,Y
15,16,1065,Network Child Care Services - Child's Nest Ear...,Non Profit Agency,121 COSBURN AVE,M4J 2L1,14,House,NaN,20,20,0,0,0,40,Y,Y
16,17,1067,Martingrove Child Care Centre,Commercial Agency,256 JOHN GARLAND BLVD,M9V 1N8,1,House,NaN,0,15,24,10,15,64,Y,Y
17,18,1070,Discovery Place Child Care Centre Ltd.,Commercial Agency,22 TUXEDO CRT,M1G 3S3,24,Purpose Built,NaN,10,20,48,20,45,143,Y,Y
18,19,1072,Carefree Preschool,Commercial Agency,370 DIXON RD,M9R 1T2,1,High Rise Apartment,NaN,20,15,48,0,0,83,N,Y
19,20,1079,East Scarb. Boys' & Girls' Club - Eastside Chi...,Non Profit Agency,20 WALDOCK ST,M1E 2E5,24,Public Elementary School,Eastview Public School,0,15,24,26,45,110,Y,Y
20,21,1082,Macaulay Child Development - Regent Street,Non Profit Agency,48 REGENT ST,M6N 3N9,5,Synagogue,NaN,10,10,24,0,0,44,Y,Y
21,22,1083,Lori Gardens Centre For Early Learning,Commercial Agency,2405 FINCH AVE W,M9M 2X2,7,High Rise Apartment,NaN,10,15,28,22,25,100,Y,Y
22,23,1086,Network - Child's Nest Early Years And Child C...,Non Profit Agency,123 COSBURN AVE,M4J 2L1,14,House,NaN,0,10,48,0,0,58,Y,Y
23,24,1091,Eastside Club Day Care - 100 Galloway Road,Non Profit Agency,100 GALLOWAY RD,M1E 1W7,24,Community/Recreation Centre,NaN,10,15,24,0,0,49,Y,Y
24,25,1093,Martin Luther Child Care - Superior,Non Profit Agency,5 SUPERIOR AVE,M8V 2M1,3,House,NaN,0,10,16,0,0,26,Y,Y

In [ ]:
# Displaying total length of dataframe

len(df)

1063

In [21]:
# Surveying columns

df.columns

Index(['_id', 'LOC_ID', 'LOC_NAME', 'AUSPICE', 'ADDRESS', 'PCODE', 'ward',
       'bldg_type', 'BLDGNAME', 'IGSPACE', 'TGSPACE', 'PGSPACE', 'KGSPACE',
       'SGSPACE', 'TOTSPACE', 'subsidy', 'cwelcc_flag'],
      dtype='object')

In [22]:
# Surveying column data types

df.dtypes

_id             int64
LOC_ID          int64
LOC_NAME       object
AUSPICE        object
ADDRESS        object
PCODE          object
ward            int64
bldg_type      object
BLDGNAME       object
IGSPACE         int64
TGSPACE         int64
PGSPACE         int64
KGSPACE         int64
SGSPACE         int64
TOTSPACE        int64
subsidy        object
cwelcc_flag    object
dtype: object

In [71]:
# Data Cleaning

## Removing columns for Research Question 1
dfRemove = ['LOC_ID', 'LOC_NAME', 'ADDRESS', 'PCODE', 'bldg_type', 'ward', 'BLDGNAME']

## Making new dataframe for Research Question 1
dfc = df.drop(dfRemove, axis='columns')

## Setting index for dataframe
dfc.set_index('_id', inplace=True)

## Grouping by Auspice for Research Question 1
##dfc = dfc.groupby('AUSPICE')

## Surveying first rows of cleaned dataframe
dfc.head(25)

,AUSPICE,IGSPACE,TGSPACE,PGSPACE,KGSPACE,SGSPACE,TOTSPACE,subsidy,cwelcc_flag
_id,,,,,,,,,
1,Non Profit Agency,0,20,32,52,60,164,Y,Y
2,Non Profit Agency,0,0,12,26,45,83,Y,Y
3,Non Profit Agency,0,10,16,26,50,102,Y,Y
4,Non Profit Agency,10,15,40,0,0,65,Y,Y
5,Non Profit Agency,0,10,16,0,0,26,Y,Y
6,Non Profit Agency,10,20,32,0,0,62,Y,Y
7,Non Profit Agency,10,15,24,0,0,49,Y,Y
8,Commercial Agency,0,0,16,0,30,46,Y,Y
9,Non Profit Agency,0,0,21,0,30,51,Y,Y
10,Non Profit Agency,0,0,24,39,90,153,Y,Y
11,Non Profit Agency,0,15,32,52,90,189,Y,Y
12,Commercial Agency,10,10,32,12,30,94,Y,Y
13,Non Profit Agency,0,0,32,52,100,184,Y,Y
14,Non Profit Agency,0,0,16,52,75,143,Y,Y
15,Non Profit Agency,0,10,16,25,30,81,Y,Y
16,Non Profit Agency,20,20,0,0,0,40,Y,Y
17,Commercial Agency,0,15,24,10,15,64,Y,Y
18,Commercial Agency,10,20,48,20,45,143,Y,Y
19,Commercial Agency,20,15,48,0,0,83,N,Y
20,Non Profit Agency,0,15,24,26,45,110,Y,Y
21,Non Profit Agency,10,10,24,0,0,44,Y,Y
22,Commercial Agency,10,15,28,22,25,100,Y,Y
23,Non Profit Agency,0,10,48,0,0,58,Y,Y
24,Non Profit Agency,10,15,24,0,0,49,Y,Y
25,Non Profit Agency,0,10,16,0,0,26,Y,Y

In [ ]:
## Exploring dataframe using a boxplot

ax = sns.boxplot(x='AUSPICE', y='TOTSPACE', data=dfc, color='#99c2a2')
ax = sns.swarmplot(x="AUSPICE", y="TOTSPACE", data=dfc, color='#7d0013')
plt.show()

In [104]:
# Assumption 1: Testing the normality-of-residuals assumption for ANOVA using a Shapiro-Wilk test

## Ordinary Least Squares (OLS) model
model = sm.OLS.from_formula('TOTSPACE ~ C(AUSPICE)', data=dfc)
result = model.fit()
residuals = result.resid

### Performing Shapiro-Wilk test for normality of residuals
shapiro_statistic, shapiro_p_value = shapiro(residuals)

print("Shapiro-Wilk Test Statistic:", shapiro_statistic)
print("p-value:", shapiro_p_value)

## Transforming the TOTSPACE data using the Box-Cox method
bcTOTSPACE, lambda_value = stats.boxcox(dfc['TOTSPACE'])

### Adding the transformed TOTSPACE data as a column in the main dataframe for later use
dfc['bcTOTSPACE'] = bcTOTSPACE

## Re-making OLS model and re-running Shapiro-Wilk test
model2 = sm.OLS.from_formula('bcTOTSPACE ~ C(AUSPICE)', data=dfc)
result2 = model2.fit()
residuals2 = result2.resid

shapiro_statistic2, shapiro_p_value2 = shapiro(residuals2)

print("Shapiro-Wilk Test Statistic for transformed data:", shapiro_statistic2)
print("p-value for transformed data:", shapiro_p_value2)

Shapiro-Wilk Test Statistic: 0.901775598526001
p-value: 1.4964898448030214e-25
Shapiro-Wilk Test Statistic for transformed data: 0.9970179200172424
p-value for transformed data: 0.04397028312087059

In [107]:
# Assumption 2: Testing the homogeneity of variances for ANOVA using a Brown-Forsythe test, a variant of Levene's test

## Performing the initial Brown-Forsythe test
bf_test_statistic, bf_p_value = levene(*[group['bcTOTSPACE'] for _, group in dfc.groupby('AUSPICE')], center='median')
print("Brown-Forsythe Test Statistic:", bf_test_statistic)
print("p-value:", bf_p_value)
print()

## Transforming the Box-Cox-transformed TOTSPACE values further by taking their square root
sqrtbcTOTSPACE = np.sqrt(bcTOTSPACE)
dfc['sqrtbcTOTSPACE'] = sqrtbcTOTSPACE

# Performing Brown-Forsythe test again on the additionally transformed data
bf_test_statistic, bf_p_value = levene(*[group['sqrtbcTOTSPACE'] for _, group in dfc.groupby('AUSPICE')], center='median')

print("Brown-Forsythe Test Statistic for transformed data:", bf_test_statistic)
print("p-value for transformed data:", bf_p_value)

Brown-Forsythe Test Statistic: 7.658715226832124
p-value: 0.0004985000712020204

Brown-Forsythe Test Statistic for transformed data: 5.005930697228283
p-value for transformed data: 0.0068573265907701944

In [115]:
# One-way ANOVA for Research Question 1

## Ordinary Least Squares (OLS) model
RQ1model = ols('sqrtbcTOTSPACE ~ C(AUSPICE)', data=dfc).fit()

## Displaying ANOVA table
anova_table = sm.stats.anova_lm(RQ1model, typ=2)
print(anova_table)

               sum_sq      df          F        PR(>F)
C(AUSPICE)   1.980386     2.0  18.248358  1.615179e-08
Residual    57.517753  1060.0        NaN           NaN

In [118]:
# Post-hoc Tukey test for Research Question 1

## Performing the Tukey test
tukey_result = pairwise_tukeyhsd(dfc['sqrtbcTOTSPACE'], dfc['AUSPICE'])

## Displaying test results
print(tukey_result.summary())

                 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================================================
      group1                  group2            meandiff p-adj   lower  upper  reject
-------------------------------------------------------------------------------------
Commercial Agency             Non Profit Agency    0.077    0.0  0.0402 0.1139   True
Commercial Agency Public (City Operated) Agency   -0.081 0.1011 -0.1737 0.0118  False
Non Profit Agency Public (City Operated) Agency   -0.158 0.0001 -0.2479 -0.068   True
-------------------------------------------------------------------------------------

In [120]:
# Research Question 2

## Creating OLS model
modelRQ2=ols('sqrtbcTOTSPACE ~ C(AUSPICE) + C(cwelcc_flag) + C(AUSPICE):C(cwelcc_flag)', data=dfc).fit()

## Producing ANOVA table
anova_tableRQ2 = sm.stats.anova_lm(modelRQ2, typ=2)
anova_tableRQ2

/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 2, but rank is 1
  warnings.warn('covariance of constraints does not have full '

                              sum_sq      df          F        PR(>F)
C(AUSPICE)                  1.626451     2.0  15.760485  7.674365e-05
C(cwelcc_flag)              2.123645     1.0  41.156704  2.115079e-10
C(AUSPICE):C(cwelcc_flag)   1.030289     2.0   9.983611  5.065002e-05
Residual                   54.591740  1058.0        NaN           NaN